{% set name = "cybuffer" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c043e5560ba095fe3af839fd3fca713cc3183b348f742eca8535abcd4427e34b

build:
  number: 1002
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - cython >=0.27.3
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - cybuffer
  requires:
    - pytest >=3.8.1
    - numpy >=1.15.2
  commands:
    - pytest

about:
  home: https://github.com/jakirkham/cybuffer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python 2/3 compatible buffer in Cython
  doc_url: https://cybuffer.readthedocs.io
  dev_url: https://github.com/jakirkham/cybuffer

extra:
  recipe-maintainers:
    - jakirkham
